spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=utf-8
      username: root
      driver-class-name: com.mysql.jdbc.Driver
      pool-name: HikariPool-1
      maximum-pool-size: 100
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
    secondary:
      jdbc-url: jdbc:mysql://localhost:3316/db?useUnicode=true&characterEncoding=utf-8
      username: root
      driver-class-name: com.mysql.jdbc.Driver
      pool-name: HikariPool-2
      maximum-pool-size: 100
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000

mybatis:
  type-aliases-package: org.geek.dynamic01.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:mapper/*.xml