


mybatis:
  type-aliases-package: org.geek.dynamic01.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:mapper/*.xml